abstract class SoundCloudMusicManagerStates{}

class SoundCloudMusicManagerInitialState extends SoundCloudMusicManagerStates{}
class SoundCloudMusicManagerLoadingState extends SoundCloudMusicManagerStates{}
class SoundCloudPlayingNowState extends SoundCloudMusicManagerStates{}
class SoundCloudPausedState extends SoundCloudMusicManagerStates{}
class SoundCloudGotTrackDataState extends SoundCloudMusicManagerStates{}
class SoundCloudMoveSliderState extends SoundCloudMusicManagerStates{}


class SoundCloudAddPlaylistSuccessState extends SoundCloudMusicManagerStates{}
class SoundCloudAddPlaylistErrorState extends SoundCloudMusicManagerStates{}

class SoundCloudUpdatePlaylistSuccessState extends SoundCloudMusicManagerStates{}
class SoundCloudUpdatePlaylistErrorState extends SoundCloudMusicManagerStates{}