abstract class SoundCloudMusicManagerStates{}

class SoundCloudMusicManagerInitialState extends SoundCloudMusicManagerStates{}
class SoundCloudMusicManagerLoadingState extends SoundCloudMusicManagerStates{}
class SoundCloudPlayingNowState extends SoundCloudMusicManagerStates{}
class SoundCloudPausedState extends SoundCloudMusicManagerStates{}
class SoundCloudGotTrackAndPlaylistsState extends SoundCloudMusicManagerStates{}
class SoundCloudMoveSliderState extends SoundCloudMusicManagerStates{}

class SoundCloudPlaylistsLoadedSuccessState extends SoundCloudMusicManagerStates{}
class SoundCloudPlaylistsLoadedErrorState extends SoundCloudMusicManagerStates{}


class SoundCloudAddPlaylistSuccessState extends SoundCloudMusicManagerStates{}
class SoundCloudAddPlaylistErrorState extends SoundCloudMusicManagerStates{}

class SoundCloudUpdatePlaylistSuccessState extends SoundCloudMusicManagerStates{}
class SoundCloudUpdatePlaylistErrorState extends SoundCloudMusicManagerStates{}